### ISSUE TITLE
Doctl Returns 500 Error When deploying App.yaml file

### ISSUE THREAD

**Issue by LuisOsta** [digitalocean/sample-monorepo#2]
Hi, I wasn't sure where to create an issue/reach out. So I thought this might be a good place to reach out. I've created a YAML spec for my DO App Platform based on the sample on this repository. 

Which looks like this:
```
name: unique-expressions

services:
  - name: api
    environment_slug: node-js
    github:
      repo: Valencian-Digital/unique-expressions
      branch: main
      deploy_on_push: true
    source_dir: api
    routes:
      - path: /api

```
But when I try to execute 
`doctl apps create --spec .do/app.yaml`
It returns a 500 Error and nothing else. I've tried executing the command both in a Github action and locally with different API tokens. I'm able to access other resources on my DO account but I can't successfully create the spec.

Do you know what could be going wrong?
