### ISSUE TITLE
Laravel in a monorepo fails with heroku-php-apache2

### ISSUE THREAD

**Issue by espensgr** [digitalocean/sample-monorepo#4]
I have tried to make a monorepo with Nuxt (frontend) and Laravel (backend) and use `doctl` to create an app.
So i copied the [sample-laravel](https://github.com/digitalocean/sample-laravel) to the backend folder and run it with all the yaml settings from the functioning sample laravel demo.
But i get `bash: heroku-php-apache2: command not found` on every try.
I tried to add a `Procfile` with `web: vendor/bin/heroku-php-apache2 public/`, still the same.
I think maybe it is because of the `source_dir` in the yaml, but dont know how to fix it.

Is it something i'm missing here or is it expected? Or can i use something else to run the php service?

**Comment by kamaln7** [comment]
Hi @espensgr,

Can you share your app spec please? The `source_dir` field changes the working directory before the build is started, so it should be the only change that's necessary for a monorepo.

Also, make sure you're using the latest version of [doctl](https://github.com/digitalocean/doctl/releases/latest). Older versions that were released before certain fields were added to the app spec will silently ignore them and not include them in the API requests.

**Comment by espensgr** [comment]
Hi @kamaln7,

i have even made you a [test repo](https://github.com/espensgr/do-monorepo-test.git) 😲 
Just a copy of the [sample-laravel](https://github.com/digitalocean/sample-laravel) in a folder, and ran `composer install` locally.
Here is the spec if you need it:

```
name: sample-laravel
services:
  - environment_slug: php
    git:
      branch: master
      repo_clone_url: https://github.com/espensgr/do-monorepo-test.git
    envs:
      - key: APP_KEY
        value: "base64:UdAH2B63rlotjrkSSsj3Hppy4gbfr+OeHvtSdF9r9q8="
    name: sample-laravel
    source_dir: laravel
    run_command: heroku-php-apache2 public/
```

Yeah i thought so too, so i dont get it.
I had the 1.54.0, but updated to 1.54.1, so dont think thats the issue.
It may be
